apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis-additional.conf: |
    slowlog-max-len 158
    stream-node-max-bytes 2048
    maxmemory 450mb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    rdbcompression yes
    rdbchecksum yes
    loglevel notice
    timeout 300
    tcp-keepalive 120
