apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-security
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/production/security
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-common
  timeout: 10m
