apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud-nextcloud
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/deploy/nextcloud
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: security-cert-manager
    - name: security-secrets-reflector
    - name: ingress-traefik
    - name: persistence-postgres
    - name: persistence-redis
  timeout: 30m
  wait: true
