apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- operator.yaml
- secrets/postgres-superuser-secret.yaml
- secrets/postgres-backup-secret.yaml
- secrets/postgres-nextcloud-secret.yaml
- cluster.yaml
- connection-pooler.yaml
- scheduled-backup.yaml
