apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sealed-secrets/postgres-superuser-srt.yaml
- sealed-secrets/postgres-backup-srt.yaml
- sealed-secrets/postgres-nextcloud-srt.yaml
- cluster.yaml
- connection-pooler.yaml
- scheduled-backup.yaml
