apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: persistence-redis
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/deploy/persistence/redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: system-operators-olm
  timeout: 30m
  wait: true
