apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: persistence-postgres
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/deploy/persistence
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: security-cert-manager
    - name: security-cluster-issuer
    - name: ingress-traefik
    - name: dashboard-headlamp
  timeout: 15m
