apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security-secrets-reflector
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/deploy/security/secrets-reflector
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 30m
