apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security-cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/deploy/security/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 30m
  wait: true
