apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security-cluster-issuer
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/deploy/security/cluster-issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: security-cert-manager
  timeout: 30m
