apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-operators-olm
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/deploy/operators-olm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 30m
  wait: true
