apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-user-secret
  namespace: persistence
spec:
  encryptedData:
    password: AgBzSVcToydPxSVJLFGjt7SdADHpgLaFV3wMj80dkbHUaiKE2mRDdX3A18qNLG6Egse+p82IphtjxBN7YaqcycA+6/HGbzX3tyZyT3o/qAzgdiOWPddc+8kG1W1nlxMhMiOS6tcKbD75NYfJPofmD9sGIup0b2Zq6pFwyMjwpYZUiU7Q9G0X3N0OrzzIxX3m3XbqcTsyn9ksdtdFQBGFRKrNHDINJ5VFWkIZebz/od1tll+rKOvyxx7xMnW0UHhEiGPlKHsb7VY/nW23aUeZzFz6kcQr08/Qc2UPqNRuXF84XBMj6zOfB+njFVLtvRwVjf90sAFqmD6CAZySb77xbez+TFzpocg2eXLZGfR308adbMPTmzuM+Kkex0NTLor9H6G2pFcxqnkeAYDm95a/SA8ZiPg7r39khKndNIYrUspFpcMCfe80nBZa95f4gvRyk+m5wRsCgvUvqtiZTezu5ch1B37Q6i7M14Itn1FucPHlBi6sas80BczoLsVywvlDiUs4VusFkziB/1b1UGHl1KDw2Rp3DErt2WyULW1nOHT6RmZbVorJpLHXEMspQ56kOsCxBigVbBz+X+p0gf9PZJtB1nuGcvWP1Uxjbt1AWH1BI8FRaz3gw9CGIHH+h0RNMUmmVIpU71O1uAikxqCDnQtjlSBSxN+ohB9zdG5ZoZ+Dr86kqJE2HtUdOhfuJSXwGuBieKEHf9ohN69Xs1iKJb3WcSXpFg/XLg==
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: nextcloud
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: nextcloud
      name: redis-user-secret
      namespace: persistence
    type: Opaque
