apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ref-grant.yaml
- route-middleware.yaml
- secrets/nextcloud-admin-secret.yaml
- secrets/nextcloud-s3-primary-secret.yaml
- release.yaml
