apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 24h
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    semver: "18.2.3"
