apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-nextcloud
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/production/nextcloud
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: persistence
  timeout: 30m
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
      namespace: flux-system
