apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-traefik
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/basecamp-0/ingress/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: security-cert-manager
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: security
  timeout: 15m
