apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security-cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/basecamp-0/security/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: security
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-cainjector
      namespace: security
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-webhook
      namespace: security
