apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-common
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/production/common
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m
