apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-superuser-secret
  namespace: persistence
spec:
  encryptedData:
    password: AgDSTdGz9mpvjLu1PMXyb53szAIDvHwoaHzndMkrZe6V2LNjk4h1qCgHiYcTSK4ULh4MIE5ENH/ZQKN1960muhmUmw+YKJ1RDeCkcvcPn1lcaCjI4QQKYi4uXJsM9KcDbl9wKxTM4lPucJxpP3tiJAcPHlwELjFOtfezBNhZ35btnFXOVrfU94o/lJB2HSD8FMZ7jK2cFY2a3Vs4JgbK4wpKwklzuWKHExQ0JVF7xkR7NMTpZo2m6BPQJ0HxhyBy5AzOBo15Vwa0wR6EYWKuS4kyF5Lq2EErFYwyOUmgVw0o1meQJMDCH/idVFOflM9e42oiJofjjcmtXx45uwT23VkpMyVJMY7O+fVZ3PSYlDUnGqi2VROiGe8SPIPhhh4VLIyI560vQBp9Hrkjr47hMLpc7Y4UahbkKtGmnaEcAEVgLwJrTIl1eTe+VYOHEPFG1K7gihtK5Uy9EAo8bKrN2xQk6KWvgixEstX7PMRGT1vexaw+N0g9TZO0h6iG8Dd1YcyT1OQUSsdmMu7tnB2vWoucvtK465K1TmN6VRERobOkEp7Q2LfbXAsxxMOeJ3IsRsji80JBIE7L9s6cE2Uj64zFixSIV8sbmrC0yQsoCFi+v8hzLzMv8iSsHxwlv/BRAGIxBUigwl8NGKhCTy0Hy+TpKu5juspcgvyv80JtA2zsM+zjGls+3jspKY7kq08NIJQ7a8Ly+BweGA5d0bat3B/MHIRlrQ==
    username: AgAymyO5U0vhwXWSAjh7szuWCV1+a2/QCSdt5S7TbaDKWuXr4yh/rS8AeYOgqd1DaCkF1kb6aODs9nhUatryFkxv/TyxCynlUpZRJMvpAEvquaPj1u2LmIS9DWqsP30ZpK/fUm2RqJ2azQVKL6r6h2DJzTH+sNsyakRr56AqYzf/8cpIDEOtL6gDkBEQAizGyuNVYtCkYveUxLFtVM0xRuA8K+H7CDa7E5rwN3ls5vqSsSLNdZ72qRn5u7R0qb4eR2OyrNTtSmkRbzmQvRS+ro4lcAQRcz+JlHmyBZpYe4ZnS1/GVdBWAVaa1L1KW/znY4Jl+te6O9OSomp2UUBGEOlQejEzU26/8oyoa5QkG71ua16Dm47vT7SXYPVDDvGhx01r36lJUHpMDvUOh3GND55d4R9BzN6AN0NhLv90/U0Bnp8v+NcuNgVZFL7tAuYo1c4VWu5dclDRYEafnFqqSEbpcJX06EnGaKYNXRTWkxHRzxsO8vQRl0GUEKuDFBlF8lIUUHdVmgXu8OQVdVH/2W/8qmTOt5+PsWqYOBCM+TwDf7+GHkAxHGsuPKv6U22hMiwhquNBLoKNfR6RmWnzzSIJq+dAvxAQPENsOR6Gavqc5anw6MZ9Lxz0RUpGTQQoZJkbpxEz4Dndo61AJYkuhTRgUEUA9Tiw+Zj6UM0y13P84+DaD6C7UR/3IRivUoS4pW7iEk3s+Hs2Sg==
  template:
    metadata:
      name: postgres-superuser-secret
      namespace: persistence
    type: kubernetes.io/basic-auth
