apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-superuser-secret
  namespace: persistence
spec:
  encryptedData:
    password: AgCbka6hkhYHCJznECUEU0nyx8nxC+fch40K3XvytuvuZ5epdscx3DsLqBVxQMlmcUtJOObBD3xqNec84MlT1AeGRXJVKMct3+BVSL3dcVVoY1P+hhSUNC+c32bIb2o2aBPWF7FynWaZyvRvmU/GR1U2v7P+XIFnUTYTQ+oF7Nj3BpA0LOrfr0ARPx2gOLJAAj0h4OdmWHwGoxMqlV/Q4dpfSUDnnfDbHKdloSomif3hJK64LPMsdk+7hRP9M7foE1gnMumSFmtiuOHSyCtvK9PgrJ4VLVQLFsypSRJcc73c2oHHb1QfX1RWc0g6Nmh3SaPd18tc8W3HtLI/AqGTrYT2Hh3v6MoLi29F/gtAyDIt0Dganw9Vh9LDsu0BuUZjvc0LSfPqyQMenrukztkAh4xCdF0guuAflob2IOThTgX1zy+MCQTiLMU9ig0oekYpu2f5NmxPa/bZ6MZRrH0jme9lsI1s/NO/twFVXuU02DcneL21B4e/u718Sx9rNV0hYntIF4twWRdokCdLXroPEWGWyUfL6yyxS7c7WZ33BKX1vfDbVCLDnffr+hOvPfbeZbs1FzF3OBjm6GSr/YygyueISr+UU7hLIWKAEcg5hPygvmIf7wqQf0aAUC6NQ42jLkeuk2jqzWPh7L3attxKwPIQ/BBcX5IFpkNgnRzhqBBxWKLVxtb6gXQ2H/8uJiezMZFjsWwZ1ObMT5pbnbdP6Sp66r6XOg==
    username: AgBCI5g6nZcuHb5QDqfC6Xzu+hNBCnDD63U4gkU72JDqAAVdhTJrsWDDzLBK8p31lOxrhzevl0QnqSxBsEPqIGjr5Pq1wJ258vxf7i957YtG+VWbmMrprmiOX0RHamVfOiM8zccmYw7qg1fzSLd5Pp+3wS87sNCyLtgmr3RqR7K1P3To+TJa9IGIl4D2T8/emqk0e22XXXksz1JAAO3woD6ffEUwXsKC0RvdemdDGPncLH5gTJDBf5vPlrnwPiAY4p/74rkE2CrT8FsGJ9u4SG9jqDrAhWIQH9ujJkt8mToxX5RzAkL90uc4QT0fEwQQGeiXF/Eqz4Cmc/xpw+e4rWmuwY9zIJRSsSaGcorneR4KMy2PuhUEjwn3C9poExhe0pL5D5MjszwwcK4GMgGNbeVQLhxyM7PpUG0wWjEVInNug5QgcEhUdVtWYZ0x1cUeMNdCB55cOl6adR5iSyY/Hatr/zroMFoIIrA7B1TQANVRlkjEPs2UkM5JxojtR2BemzOkZrsFWe8GitnYBvwRcUjJ2oBof804TYaSriiXPApxPDm+Qn2B3v/1AVwJ9ti1Kz0C/bX9PKCvJ1+BGK9IYAOWf+g1RFMX2aj9FdbLWj4+rBuOev47FFhRrf5QaNwLOCg+vzguMBfh8ITYzmtCQF7zycukiB9jrBjHEg9KcVPiIFs9nBsnjMxdCt3reL+FK29+uVPVFw8aKA==
  template:
    metadata:
      name: postgres-superuser-secret
      namespace: persistence
    type: kubernetes.io/basic-auth
