apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-superuser-secret
  namespace: persistence
spec:
  encryptedData:
    password: AgBVy6Bku9x7zAOVEDJLbF2sJdWgwvD0xZRe16bQwvYgu1EkzHLPEl9VyC2d5nmwZ0pFJrIxxi6SuQhH63vhbc1tEd0RbEVaeip6D4FjKGOCI+kMccq15tzrXIs9+cL3bdwE8jph7f63rvUJpyGC634wgvhFPAzQUFbakTxu1YQtCc2KnllZ4QZV5WnGakrDvI20jxMzmqR5arW5LK581X8HOp3wkeyMyVNew5xB/x+/CkpQPlBUHoGRfoIMtQCwmAzATUk/21GvSCm7k1WO4S0QawRlDpwOFljMOqRj4QJx83DklusERhTLKFkDIYZWs78fA6KSrW/RMRbddHvxg5xiGz/dbPoj1QIhB45CY1Io7r+sOPrZ/FZdx9SQPv6sxYJatckq1HjtIhHdY6RjL3PeXvyepLS0kM92H+QS9cXr94ifNyNnk6evPEcc9NMbpsibaL0W70rEJPJ5C5swiJ3HWx+1MB0cFN2VHyUjgHjvu5v/Bb3Q33qUudDAr+ykyniQ70G4gq9pR+s8eFXLON42Kn1VEgF3Ap/2EeUQvnPdMH814qQ9Tvv8q+GeYHwcWjkNuqjIeMF9wIc+bBSpzjOExfxsEs9GO6800Q5cRaCq3A3yItXiCmMVwLx1gu46Vnb6YW9KegQfkpr4eqkQ/dkEdulILw/II0+9ENt/ry7gVdwWkQAdwoFQbtm52+ALiIwfWTRB/RtExMZ7nibmuoyEs095Bg==
    username: AgBnoYSpgFbRLN1tiixJOLgGpCxXluFZk7bSvj1CVjU7C38qOxvCDbGy9VL5KJ1RAI1ZjLEmlGxJPRxHmQACpOwzsRDHR9T86irdQtieDS0fbjcGX6Cd0hiedINglj4E1OimIq3ZpM4gjlOss7DVdyGcgADbfKZspw4TFqGyriiKHW0vLNWjJvtFdPd0upnFQPJ175Un7iFsP7ASg7ePgetU2jmSoNM5eaCMW9jJeiTT+aqQ86s8P1Rcky/Rz5EdZqc8C2lmQRH9D3KwfH/uKbDeJu3r2bQ/uurHZLW27l0p4SUjzWqCP5q3AZ6yvM3KwX7uKM/2B8CsJjeDrHFDzvNZv7AQ0E7RfiP70QTrrX6V6jiaJAjWwws4wnL+QEkVL9Yeb5qEUo7bqvTQqCbFZ8GbKvmdw3cfskZTmiIwC6TsafJkzzfmZsNxo/Hl12eSYwtp2jx1KRG53QTi48U397nwibzUUIm2RjX3SMF4I9AGGGhUFyBKoGPh1HVy4XyT9P9BwSrwNoJ9wmlQ9idQKuboio6tnPaTl1UM9VDMh2UB0Q9YJXvbjb8UoYmwDXO4lQknUlym1Z6vqXEcjPnjKJevDMfezbrVoQhdZLKOhwLxuld64JqKb7n02NiEHDlhHcoZx9SEkaVSEl+AA4ZaWWrLXEcDV/Kbh/c3+MOb5Fqq6BBLLeTK1lC0XA81O03/n2hrkfJF8SqMXA==
  template:
    metadata:
      name: postgres-superuser-secret
      namespace: persistence
    type: kubernetes.io/basic-auth
