apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-ingress-to-nextcloud
  namespace: nextcloud
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: Gateway
    namespace: ingress
  to:
  - group: ""
    kind: Service
