apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-redirects
  namespace: nextcloud
spec:
  redirectRegex:
    # Redirects /.well-known/carddav and caldav to the internal DAV endpoint
    regex: ^/.well-known/(carddav|caldav)
    replacement: /remote.php/dav/
    permanent: true
