apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external-gateway
  namespace: ingress
  annotations:
    traefik.io/entrypoints: web,websecure
    cert-manager.io/cluster-issuer: letsencrypt-dev
spec:
  gatewayClassName: traefik
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All

  - name: https-dashboard
    protocol: HTTPS
    port: 443
    hostname: "dashboard.sigdep.cloud"
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: dashboard-ingress-gateway-cert
        namespace: ingress
    allowedRoutes:
      namespaces:
        from: All

  - name: https-drive
    protocol: HTTPS
    port: 443
    hostname: "drive.sigdep.cloud"
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: drive-ingress-gateway-cert
        namespace: ingress
    allowedRoutes:
      namespaces:
        from: All

  - name: https-app
    protocol: HTTPS
    port: 443
    hostname: "app.sigdep.cloud"
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        name: app-ingress-gateway-cert
        namespace: ingress
    allowedRoutes:
      namespaces:
        from: All
