apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-persistence
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/production/persistence
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-kube-system
    - name: flux-olm
  timeout: 30m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
